# Generated by Django 3.1 on 2020-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('MO', 'moderator'), ('AD', 'admin')], default='US', max_length=2),
        ),
    ]
