# Generated by Django 3.1 on 2020-10-07 14:18

from django.db import migrations, models
import titles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[titles.validators.validate_score], verbose_name='Оценка'),
        ),
    ]
