# Generated by Django 3.1 on 2020-10-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20201006_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
    ]
