# Generated by Django 3.1 on 2020-10-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
