# Generated by Django 3.1 on 2020-10-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20201007_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
    ]
